import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavigationBar from "../components/navigationBar";
import Card from "../components/cards";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar />
      <div className="container mx-auto w-full flex">
        <Card />
        <Card />
        <Card />
      </div>
    </div>
  );
}
